package Exception;

public class use_of_throw {
	public static void main(String[] args) throws Throwable    {
		System.out.println("hii");
		Thread.sleep(2000);

}
}
